name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          ignore_words_list: iam,aks
          check_filenames: true
          check_hidden: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v3.3.0

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --config ct.yaml)
      #     if [[ -n "$changed" ]]; then
      #       echo "::set-output name=changed::true"
      #     fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        # if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml

  dry-release:
    runs-on: ubuntu-latest
    needs:
      - lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Fetch history
      #   run: git fetch --prune --unshallow

      - name: Helm Chart Publish
        uses: buttahtoast/helm-release-action@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dryrun: true